# Generated by Django 3.1.3 on 2021-03-18 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210316_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrel',
            name='pull_date',
        ),
        migrations.AddField(
            model_name='barrel',
            name='actual_pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 15, 43, 12, 695282)),
        ),
        migrations.AddField(
            model_name='barrel',
            name='estimated_pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 15, 43, 12, 695250)),
        ),
    ]
