# Generated by Django 3.1.3 on 2021-03-26 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210318_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrel',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 13, 23, 36, 36932)),
        ),
    ]
