# Generated by Django 3.1.3 on 2021-03-27 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20210327_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrel',
            name='beer_style',
            field=models.CharField(choices=[('Sour', 'Sour'), ('Stout_Porter', 'Stout_Porter'), ('Lager', 'Lager'), ('Belgian', 'Belgian'), ('Specialty', 'Specialty')], default='Stout_Porter', max_length=16),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 12, 9, 46, 172518)),
        ),
    ]
