# Generated by Django 3.1.3 on 2021-04-01 20:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20210401_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 20, 30, 8, 891073)),
        ),
    ]
