# Generated by Django 3.1.3 on 2021-04-02 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20210401_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 13, 33, 42, 719307)),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_barrel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.barrel'),
        ),
    ]
