# Generated by Django 3.1.3 on 2021-04-02 19:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20210402_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 19, 34, 24, 40642)),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_message', models.TextField()),
                ('alert_barrel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.barrel')),
                ('alert_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
