# Generated by Django 3.1.3 on 2021-04-02 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20210402_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 19, 42, 6, 198674)),
        ),
    ]
