# Generated by Django 3.1.3 on 2021-04-02 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20210402_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 20, 0, 49, 773610)),
        ),
    ]
