# Generated by Django 3.1.3 on 2021-04-02 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_auto_20210402_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 20, 51, 0, 571265)),
        ),
    ]
