# Generated by Django 3.1.3 on 2021-04-02 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20210402_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 23, 33, 30, 728224)),
        ),
    ]
