# Generated by Django 3.1.3 on 2021-04-02 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_auto_20210402_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_off',
        ),
        migrations.AddField(
            model_name='barrel',
            name='alert_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 23, 36, 53, 429990)),
        ),
    ]
