# Generated by Django 3.1.3 on 2021-04-03 22:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_auto_20210403_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrel',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='fill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 30, 22, 46, 50, 26150)),
        ),
    ]
