# Generated by Django 3.1.3 on 2021-04-03 23:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_auto_20210403_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrel',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 23, 9, 21, 13886)),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_barrel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.barrel'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
